SAMPLE_RATE = 16000
BLOCK_SIZE = 512

ROLLING_SECONDS = 1.0
END_SILENCE_SECONDS = 2.0

ROLLING_BLOCKS = int(ROLLING_SECONDS * SAMPLE_RATE / BLOCK_SIZE)
END_SILENCE_BLOCKS = int(END_SILENCE_SECONDS * SAMPLE_RATE / BLOCK_SIZE)
